data_cfg:
  dataset_name: OccCASIA-B
  dataset_root: /home/pengyunjie/data/OccCASIA-B/occlusion64pkl
  dataset_partition: ./misc/partitions/OccCASIA-B_clean.json
  # dataset_partition: ./misc/partitions/OccCASIA-B_crowd.json
  # dataset_partition: ./misc/partitions/OccCASIA-B_detect.json
  # dataset_partition: ./misc/partitions/OccCASIA-B_static.json
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: OccCASIA-B

evaluator_cfg:
  enable_float16: false
  restore_ckpt_strict: true
  restore_hint: 40000
  save_name: baseline2d
  sampler:
    batch_size: 8
    sample_type: all_ordered
    type: InferenceSampler
  metric: euc # cos

loss_cfg:
  - loss_term_weights: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weights: 0.1
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: Baseline2d
  in_channels: [1, 32, 64, 128]
  SeparateFCs:
    in_channels: 128
    out_channels: 256
    parts_num: 32
  SeparateBNNecks:
    class_num: 74
    in_channels: 256
    parts_num: 32
  bin_num: [32]

optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 10000
    - 20000
    - 30000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  fix_BN: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 2000
  save_name: baseline2d
  sync_BN: false
  total_iter: 40000
  sampler:
    batch_shuffle: false
    batch_size:
      - 8
      - 16
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_unordered
    type: TripletSampler
