data_cfg:
  dataset_name: OccCASIA-B
  dataset_root: /home/pengyunjie/data/OccCASIA-B/occlusion64pkl
  dataset_partition: ./misc/partitions/OccCASIA-B_clean.json
  # dataset_partition: ./misc/partitions/OccCASIA-B_crowd.json
  # dataset_partition: ./misc/partitions/OccCASIA-B_detect.json
  # dataset_partition: ./misc/partitions/OccCASIA-B_static.json
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: OccCASIA-B

evaluator_cfg:
  enable_distributed: true
  enable_float16: false 
  restore_ckpt_strict: true
  restore_hint: 80000
  save_name: gaitgl
  sampler:
    batch_size: 8
    sample_type: all_ordered
    type: InferenceSampler

loss_cfg:
  - loss_term_weights: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weights: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: false
    log_prefix: softmax

model_cfg:
  model: GaitGL
  channels: [32, 64, 128]
  class_num: 74

optimizer_cfg:
  lr: 1.0e-4
  solver: Adam
  weight_decay: 5.0e-4

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 70000
  scheduler: MultiStepLR

trainer_cfg:
  enable_distributed: true
  enable_float16: false
  fix_BN: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: gaitgl
  sync_BN: true
  total_iter: 80000
  sampler:
    batch_shuffle: true
    batch_size:
      - 8
      - 8
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
